### ISSUE TITLE
May I ask if the purpose of the hpy project is to replace the cpython interpreter

### ISSUE THREAD

**Issue by xiaohuazi123** [pyhandle/hpy#37]
Although the official cpython interpreter does not have GC and GIL restrictions, it is still an official product.If hpy can replace the cpython interpreter, will it go into the official domain?

**Comment by auvipy** [comment]
Hpy won't replace CPython!

**Comment by antocuni** [comment]
HPy is NOT a Python implementation, and as such it cannot replace CPython.
HPy defines an interface between a generic interpreter and C extensions, and provides an implementation for CPython.
Eventually, CPython devs could decide to adopt HPy internally, but it is surely not going to happen any time soon.

Closing the issue. If you have more questions, the IRC channel (`#hpy` on freenode)  or the [Mailing list](hpy-dev@python.org) are probably better places to have more discussion.
