### ISSUE TITLE
Signature of HPy_New

### ISSUE THREAD

**Issue by antocuni** [pyhandle/hpy#40]
The goals of `HPy_New` are:
  1. create a new object
  2. return a handle to it
  3. return a reference to the underlying user-defined C struct, so that the user can fill its fields

Current signature and example of usage (see `test/test_hpytype.py:test_HPy_New`):
```c
HPy HPy_New(HPyContext ctx, HPy h_type, void **data);
...
PointObject *point;
HPy h_point = HPy_New(ctx, cls, &point);
point->x = 7;
point->y = 3;
```
This works, but we get a C warning, since there is an implicit cast from `PointObject**` to `void**`.
I would like to:
  1. get rid of the warning
  2. ensure a minimum level of type checking; in particular, at the moment if you declare `PointObject point` (without the star), the code still compiles but it's horribly wrong.

One idea which I had is to rename it as `_HPy_New`, and turn `HPy_New` into a macro:
```c
HPy _HPy_New(HPyContext ctx, HPy cls, void **data);
#define HPy_New(ctx, cls, data) (_HPy_New((ctx), (cls), (sizeof(**data), (void**)data)))
```

The trick is to pass `(sizeof(**data), (void**)data)` as the 3rd argument: thanks to the comma operator, the result of `sizeof()` is ignored, but we get an error if we pass something which is not a pointer to a pointer. The error is not very clear, though:
```
point.h:6:65: error: invalid type argument of unary ‘*’ (have ‘PointObject’ {aka ‘struct <anonymous>’})
 #define HPy_New(ctx, cls, data) (_HPy_New((ctx), (cls), (sizeof(**data), (void**)data)))
point.c:30:5: note: in expansion of macro ‘HPy_New’
     HPy_New(ctx, cls, &p);
```

Any better idea how to handle this?

**Comment by mattip** [comment]
I think for now that is fine.

Maybe we can add a terse comment on the line with the macro so it shows up in the error.

Better would be a  FAQ answer in the documentation with this error string and an explanation so google will guide people there.

Even better would be to add the error messasge from MSVC and clang.

**Comment by antocuni** [comment]
The idea was to open a PR but I committed to master by mistake :facepalm:. If anybody has opinions about this, feel free to reopen the issue.
