### ISSUE TITLE
Dogfooding in CPython

### ISSUE THREAD

**Issue by jdemeyer** [pyhandle/hpy#5]
Victor Stinner pointed me to this project.

If this is ever accepted, I think it's important for CPython to use this API itself for implementing external modules (e.g. `functools` or `json`). I'm regularly annoyed that the designers of the C API in CPython are often not users of that API, so they make bad choices and don't see some problems with the API (I'm talking about problems as users of the API, not as implementers of that API).

**Comment by vstinner** [comment]
CPython doesn't rely much on external projects. IMHO PyHandle is too experimental to be used inside CPython. No stable API is planned for the near future.

**Comment by jdemeyer** [comment]
> CPython doesn't rely much on external projects.

So this "PyHandle API" would be an external project, not something that CPython and PyPy itself would implement? If so, it would be good to clarify that in the proposal. If it's not officially sanctioned by CPython, I expect that it will be harder to convince people to use it.

Regardless, I think that it's hard to design a good API by guessing what other projects need. It's best to start as user of that potential new API and then see what you need.

**Comment by arigo** [comment]
The API should, of course, be reasonable to use on its own, but we're planning to design it with Cython-generated code in mind.  The first goal is that Cython generates C code that uses it.

Like cffi, you'd either use "pip install" to get the wrappers for CPython, or it would be directly included with PyPy.

Trying to freeze a version of these wrappers inside CPython itself is something we'd consider, but much later.

**Comment by antocuni** [comment]
To elaborate on what Armin said, this is the initial plan:
1. `hpy` will provide a `.h` file which implements the new API in terms of the existing C API: this will make it possible to use `hpy` on CPython
2. PyPy will implement it natively
3. Cython will use it in its generated code; this will make Cython extensions faster on PyPy, and the same speed as now on CPython
4. other extensions and modules will be able to choose whether to use `hpy` or not, to get extra performance on PyPy

Eventually, CPython might decide to adopt it as an official API and possibly migrate to it, but that's a much longer term goal.

@jdemeyer does this answer your questions? Can I close the issue?
